// lib/queue.js — Vercel-compatible version (no SSE, uses polling via /api/logs)
const {
  fetchFileContent, readDocFile, writeDocFileToBranch,
  createDocsBranch, docsBranchExists, createPullRequest,
  toDocPath, isInScope,
} = require("./github");
const { generateExplanation } = require("./huggingface");
const { Update, DocIndex }    = require("./models");

const SKIP_EXT = new Set(["png","jpg","jpeg","gif","ico","svg","woff","woff2",
  "ttf","eot","pdf","zip","tar","gz","lock","log","md"]);

function shouldProcess(filePath) {
  if (!isInScope(filePath)) return false;
  return !SKIP_EXT.has(filePath.split(".").pop().toLowerCase());
}

// ── In-memory log store (for polling) ────────────────────────────────────────
const recentLogs = [];

function log(level, filePath, message) {
  const entry = { level, filePath: filePath || null, message, ts: new Date().toISOString() };
  recentLogs.unshift(entry);
  if (recentLogs.length > 300) recentLogs.pop();
  console.log(`[${level.toUpperCase()}]`, filePath || "", message);
  return entry;
}

function getRecentLogs() { return recentLogs; }

// ── Queue state ───────────────────────────────────────────────────────────────
let queue     = [];
let isRunning = false;
let queueSize = 0;
let running   = false;

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

// ── Process one file ──────────────────────────────────────────────────────────
async function processOne(filePath, branchName, commitSha, triggeredBy) {
  const docPath = toDocPath(filePath);
  log("info", filePath, "fetching source…");

  const content = await fetchFileContent(filePath);
  if (!content || content.trim().length < 20) {
    log("skip", filePath, "empty or too small");
    await Update.create({ filePath, docPath, status:"skipped", error:"too small", commitSha, triggeredBy });
    return "skipped";
  }

  log("info", filePath, "generating explanation…");
  const existing = await readDocFile(docPath);

  let explanation;
  try {
    explanation = await generateExplanation(filePath, content, existing);
  } catch (e) {
    log("error", filePath, `HF error: ${e.message}`);
    await Update.create({ filePath, docPath, status:"error", error: e.message, commitSha, triggeredBy });
    if (e.message.includes("429")) { log("warn", null, "Rate limited — waiting 30s"); await sleep(30000); }
    return "error";
  }

  log("info", filePath, `writing to branch ${branchName}…`);
  await writeDocFileToBranch(docPath, explanation, branchName);
  await Update.create({ filePath, docPath, status:"success", commitSha, triggeredBy });
  await DocIndex.findOneAndUpdate(
    { filePath },
    { filePath, docPath, lastCommitSha: commitSha, updatedAt: new Date() },
    { upsert: true, new: true }
  );
  log("success", filePath, "✓ done");
  return "success";
}

// ── Run batch → branch → PR ───────────────────────────────────────────────────
async function runBatch(files, commitSha, triggeredBy) {
  const ts         = Date.now();
  const shortSha   = commitSha ? commitSha.slice(0,7) : "manual";
  const branchName = `docs/auto-${shortSha}-${ts}`;

  log("queue", null, `Creating branch: ${branchName}`);
  try { await createDocsBranch(branchName); }
  catch (e) { if (!(await docsBranchExists(branchName))) { log("error", null, `Branch failed: ${e.message}`); return; } }

  const results = { success:0, error:0, skipped:0 };
  const succeeded = [];

  for (const filePath of files) {
    queueSize = Math.max(0, queueSize - 1);
    const result = await processOne(filePath, branchName, commitSha, triggeredBy);
    results[result] = (results[result] || 0) + 1;
    if (result === "success") succeeded.push(filePath);
    await sleep(2500);
  }

  if (succeeded.length > 0) {
    log("info", null, `Opening PR for ${succeeded.length} file(s)…`);
    const fileList = succeeded.map(f => `- \`${f}\` → \`${toDocPath(f)}\``).join("\n");
    try {
      const prUrl = await createPullRequest({
        branchName,
        title: `docs: auto-update ${succeeded.length} file(s) [${shortSha}]`,
        body: `## Automated Documentation Update\n\nTriggered by: ${triggeredBy}\n\n### Files\n\n${fileList}\n\n---\n*Generated by QuantumDocsSyncer*`,
      });
      log("pr", null, `PR opened → ${prUrl}`);
    } catch (e) { log("error", null, `PR failed: ${e.message}`); }
  }

  log("queue", null, `Batch done — ✓${results.success} ✗${results.error} skip${results.skipped}`);
}

// ── Queue runner ──────────────────────────────────────────────────────────────
async function runQueue() {
  if (isRunning) return;
  isRunning = true; running = true;

  while (queue.length > 0) {
    const batch = queue.splice(0, queue.length);
    const groups = {};
    for (const job of batch) {
      const key = `${job.commitSha||"manual"}::${job.triggeredBy}`;
      if (!groups[key]) groups[key] = { files:[], commitSha:job.commitSha, triggeredBy:job.triggeredBy };
      groups[key].files.push(job.filePath);
    }
    for (const g of Object.values(groups)) {
      log("queue", null, `Batch: ${g.files.length} files (${g.triggeredBy})`);
      await runBatch(g.files, g.commitSha, g.triggeredBy);
    }
  }

  isRunning = false; running = false; queueSize = 0;
  log("queue", null, "Queue finished");
}

function enqueue(files, commitSha, triggeredBy) {
  const valid = files.filter(shouldProcess);
  valid.forEach(f => queue.push({ filePath:f, commitSha:commitSha||null, triggeredBy:triggeredBy||"manual" }));
  queueSize += valid.length;
  runQueue().catch(console.error);
  return valid.length;
}

function getQueueSize()  { return queueSize; }
function isProcessing()  { return running; }

module.exports = { enqueue, getQueueSize, isProcessing, shouldProcess, getRecentLogs };