// lib/queue.js
const {
  fetchFileContent, readDocFile, writeDocFileToBranch,
  createDocsBranch, docsBranchExists, createPullRequest,
  toDocPath, isInScope,
} = require("./github");
const { generateExplanation } = require("./huggingface");
const { Update, DocIndex }    = require("./models");

// Skip .md files and binary formats inside src/ or include/
const SKIP_EXT = new Set(["png","jpg","jpeg","gif","ico","svg","woff","woff2",
  "ttf","eot","pdf","zip","tar","gz","lock","log","md"]);

function shouldProcess(filePath) {
  if (!isInScope(filePath)) return false;
  const ext = filePath.split(".").pop().toLowerCase();
  return !SKIP_EXT.has(ext);
}

// ── SSE ──────────────────────────────────────────────────────────────────────
const sseClients = [];
const recentLogs = [];

function broadcast(entry) {
  recentLogs.unshift(entry);
  if (recentLogs.length > 300) recentLogs.pop();
  const msg = `data: ${JSON.stringify(entry)}\n\n`;
  sseClients.forEach(r => { try { r.write(msg); } catch {} });
}

function log(level, filePath, message) {
  const entry = { level, filePath: filePath || null, message, ts: new Date().toISOString() };
  broadcast(entry);
  console.log(`[${level.toUpperCase()}]`, filePath || "", message);
  return entry;
}

function addSSEClient(res) {
  sseClients.push(res);
  recentLogs.slice(0, 30).reverse().forEach(l => {
    try { res.write(`data: ${JSON.stringify(l)}\n\n`); } catch {}
  });
  return () => {
    const i = sseClients.indexOf(res);
    if (i !== -1) sseClients.splice(i, 1);
  };
}

// ── Queue state ───────────────────────────────────────────────────────────────
let queue     = [];
let isRunning = false;

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

// ── Process one file onto a branch ────────────────────────────────────────────
async function processOne(filePath, branchName, commitSha, triggeredBy) {
  const docPath = toDocPath(filePath);

  log("info", filePath, "fetching source…");
  const content = await fetchFileContent(filePath);
  if (!content || content.trim().length < 20) {
    log("skip", filePath, "empty or too small");
    await Update.create({ filePath, docPath, status: "skipped", error: "too small", commitSha, triggeredBy });
    return "skipped";
  }

  log("info", filePath, "generating explanation…");
  const existing = await readDocFile(docPath);

  let explanation;
  try {
    explanation = await generateExplanation(filePath, content, existing);
  } catch (e) {
    log("error", filePath, `HF error: ${e.message}`);
    await Update.create({ filePath, docPath, status: "error", error: e.message, commitSha, triggeredBy });
    if (e.message.includes("429") || e.message.includes("rate")) {
      log("warn", null, "Rate limited — waiting 30s");
      await sleep(30000);
    }
    return "error";
  }

  log("info", filePath, `writing to branch ${branchName}…`);
  await writeDocFileToBranch(docPath, explanation, branchName);

  await Update.create({ filePath, docPath, status: "success", commitSha, triggeredBy });
  await DocIndex.findOneAndUpdate(
    { filePath },
    { filePath, docPath, lastCommitSha: commitSha, updatedAt: new Date() },
    { upsert: true, new: true }
  );

  log("success", filePath, "✓ done");
  return "success";
}

// ── Run one batch: create branch → process all → open PR ─────────────────────
async function runBatch(files, commitSha, triggeredBy) {
  const ts         = Date.now();
  const shortSha   = commitSha ? commitSha.slice(0, 7) : "manual";
  const branchName = `docs/auto-${shortSha}-${ts}`;

  log("queue", null, `Creating branch: ${branchName}`);
  try {
    await createDocsBranch(branchName);
  } catch (e) {
    if (!(await docsBranchExists(branchName))) {
      log("error", null, `Branch creation failed: ${e.message}`);
      return;
    }
  }

  const results   = { success: 0, error: 0, skipped: 0 };
  const succeeded = [];

  for (const filePath of files) {
    const result = await processOne(filePath, branchName, commitSha, triggeredBy);
    results[result] = (results[result] || 0) + 1;
    if (result === "success") succeeded.push(filePath);
    broadcast({ level: "queue_size", size: queue.length });
    await sleep(2500); // HF free tier buffer
  }

  if (succeeded.length > 0) {
    log("info", null, `Opening PR for ${succeeded.length} file(s)…`);
    const fileList = succeeded.map(f => `- \`${f}\` → \`${toDocPath(f)}\``).join("\n");
    const trigger  = triggeredBy === "webhook"
      ? `Triggered by push \`${shortSha}\``
      : "Triggered manually via QuantumDocsSyncer";

    try {
      const prUrl = await createPullRequest({
        branchName,
        title: `docs: auto-update ${succeeded.length} file(s) [${shortSha}]`,
        body: `## Automated Documentation Update\n\n${trigger}\n\n### Files Updated\n\n${fileList}\n\n---\n*Generated by QuantumDocsSyncer using HuggingFace Mistral-7B*`,
      });
      log("pr", null, `PR opened → ${prUrl}`);
      broadcast({ level: "pr", url: prUrl, fileCount: succeeded.length, ts: new Date().toISOString() });
    } catch (e) {
      log("error", null, `PR failed: ${e.message}`);
    }
  }

  log("queue", null, `Batch done — ✓${results.success} ✗${results.error} skip${results.skipped}`);
}

// ── Main queue runner ─────────────────────────────────────────────────────────
async function runQueue() {
  if (isRunning) return;
  isRunning = true;
  broadcast({ level: "running", value: true });

  while (queue.length > 0) {
    const batch = queue.splice(0, queue.length);
    broadcast({ level: "queue_size", size: 0 });

    // Group jobs by commit+trigger so each push gets its own PR
    const groups = {};
    for (const job of batch) {
      const key = `${job.commitSha || "manual"}::${job.triggeredBy}`;
      if (!groups[key]) groups[key] = { files: [], commitSha: job.commitSha, triggeredBy: job.triggeredBy };
      groups[key].files.push(job.filePath);
    }

    for (const g of Object.values(groups)) {
      log("queue", null, `Batch start: ${g.files.length} files (${g.triggeredBy})`);
      await runBatch(g.files, g.commitSha, g.triggeredBy);
    }
  }

  isRunning = false;
  broadcast({ level: "running", value: false });
  log("queue", null, "Queue finished");
  broadcast({ level: "queue_size", size: 0 });
}

// ── Public API ────────────────────────────────────────────────────────────────
function enqueue(files, commitSha, triggeredBy) {
  const valid = files.filter(shouldProcess);
  valid.forEach(f => queue.push({ filePath: f, commitSha: commitSha || null, triggeredBy: triggeredBy || "manual" }));
  broadcast({ level: "queue_size", size: queue.length });
  runQueue().catch(console.error);
  return valid.length;
}

function getQueueSize() { return queue.length; }
function isProcessing() { return isRunning; }

module.exports = { enqueue, addSSEClient, getQueueSize, isProcessing, shouldProcess };
